In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
Kentuckydf = pd.read_csv("../Data/Kentucky_Homicides.csv")

Kentuckydf

,Series,11-2020,12-2020,01-2021,02-2021,03-2021,04-2021,05-2021,06-2021,07-2021,...,02-2025,03-2025,04-2025,05-2025,06-2025,07-2025,08-2025,09-2025,10-2025,11-2025
0,Kentucky Offenses,28,37,34,18,31,23,39,40,31,...,18,13,6,7,6,14,8,11,0,NaN
1,Kentucky Clearances,12,17,22,12,19,11,17,19,13,...,10,9,7,4,4,12,4,12,0,NaN

In [ ]:
plt.pie(Kentuckydf)

In [ ]:
Indianadf = pd.read_csv("../Data/Indiana_Homicides.csv")

Indianadf

,Series,11-2020,12-2020,01-2021,02-2021,03-2021,04-2021,05-2021,06-2021,07-2021,...,02-2025,03-2025,04-2025,05-2025,06-2025,07-2025,08-2025,09-2025,10-2025,11-2025
0,Indiana Offenses,40,46,36,31,33,35,36,38,51,...,12,10,10,10,11,12,14,5,0,NaN
1,Indiana Clearances,7,17,22,18,11,12,14,10,19,...,7,7,7,4,5,3,6,1,0,NaN

In [ ]:
Illinoisdf = pd.read_csv("../Data/Illinois_Homicides.csv")

Illinoisdf

,Series,11-2020,12-2020,01-2021,02-2021,03-2021,04-2021,05-2021,06-2021,07-2021,...,02-2025,03-2025,04-2025,05-2025,06-2025,07-2025,08-2025,09-2025,10-2025,11-2025
0,Illinois Offenses,84,84,17,12,13,14,21,15,95,...,32,46,36,37,44,48,46,47,25,0
1,Illinois Clearances,3,4,7,6,5,8,10,5,11,...,21,21,21,11,10,21,13,15,11,0

In [ ]:
Ohiodf = pd.read_csv("../Data/Ohio_Homicides.csv")

Ohiodf

,Series,11-2020,12-2020,01-2021,02-2021,03-2021,04-2021,05-2021,06-2021,07-2021,...,02-2025,03-2025,04-2025,05-2025,06-2025,07-2025,08-2025,09-2025,10-2025,11-2025
0,Ohio Offenses,80,83,72,66,67,68,85,82,102,...,29,33,44,38,45,43,32,21,24,0
1,Ohio Clearances,26,38,37,29,28,19,29,30,38,...,21,20,22,15,19,26,16,18,10,1